### ISSUE TITLE
IP blocking to receive funds for the google collab notebook

### ISSUE THREAD

**Issue by sbneo2022** [NibiruChain/nibiru#1078]
<img width="977" alt="Screenshot 2022-11-23 at 2 23 57 PM" src="https://user-images.githubusercontent.com/97976373/203630651-0cf64901-9183-4451-a805-b81ef93c23c2.png">

**Comment by sbneo2022** [comment]
Some of the investors might play with the google notebook, specifically cypher capital, can someone fix this issue

**Comment by Unique-Divine** [comment]
They need to use a different address, not the default

**Comment by sbneo2022** [comment]
@helder-moreira I do a disconnect and delete to get around this problem, is there a better way to do this?

**Comment by helder-moreira** [comment]
> @helder-moreira I do a disconnect and delete to get around this problem, is there a better way to do this?

I can implement a whitelisting mechanism. Whitelist accounts and IP addresses. Should I proceed?

**Comment by Unique-Divine** [comment]
Spoke to Sankha. This is not related to IP address, just which account you use.
