### ISSUE TITLE
feat(perp): track aggregate open notional

### ISSUE THREAD

**Issue by NibiruHeisenberg** [NibiruChain/nibiru#1095]
@Unique-Divine requested a feature where the x/perps module tracks the aggregate open notional on the exchange via a monotonically increasing counter. 

The net open notional (i.e., trading volume) over a given period of time can be calculated by subtracting the aggregate open notional from the beginning of the time window from the aggregate open notional from the end of the time window.

**Comment by Unique-Divine** [comment]
Completed: Implemented by `AMM.TotalLong` and `AMM.TotalShort`

https://pkg.go.dev/github.com/NibiruChain/nibiru@v0.21.11/x/perp/v2/types#AMM

```go
	// Total long refers to the sum of long open notional in base.
	TotalLong github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,6,opt,name=total_long,json=totalLong,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"total_long"`
	// Total short refers to the sum of short open notional in base.
	TotalShort github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,7,opt,name=total_short,json=totalShort,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"total_short"`
```
