### ISSUE TITLE
refactor(perp): change `CumulativePremiumFractions` array to single value

### ISSUE THREAD

**Issue by NibiruHeisenberg** [NibiruChain/nibiru#1096]
Currently, the `CumulativePremiumFractions` is an ever-increasing array of premium fractions. We only ever use the last value in the perps module, but the array is kept around for querying historical values.

If we store the historical values in `heart-monitor` then there's no need to keep the array around, and we can refactor it to a single value.

Depends on https://github.com/NibiruChain/heart-monitor/issues/54.

**Comment by Unique-Divine** [comment]
Can you make it two values: current and last?
