### ISSUE TITLE
feat(perp): re-write swap logic using new functions

### ISSUE THREAD

**Issue by matthiasmatt** [NibiruChain/nibiru#1234]
We define the state of the pool with the Bias $B$ in base.

We have:

$$
\begin{equation}
\phi^2 = (r^b_0 + B) (r^q_0 + s_q(B)) 
\end{equation}
$$
With:
$$
s_q:\mathbb{R}\rightarrow\mathbb{R}, s_q(B) = \frac{\phi^2}{\phi + B} - r^q_0
$$

We assume that $\boxed{r^q_0=r^b_0=\phi}$. Which means that (2) becomes:

$$\begin{aligned}
\phi^2 &= (r^b_0 + B + \Delta r^b) (r^q_0 + s_q(B) + \Delta r^q) \\
\iff \phi^2 &= (\phi + B+ \Delta r^b) (\frac{\phi^2}{\phi + B  }+\Delta r^q) \\
\boxed{\Delta r^q = \frac{\phi^2}{(\phi + B+ \Delta r^b)} -\frac{\phi^2}{\phi + B }}\\
\boxed{\Delta r^b = \frac{\phi^2}{\frac{\phi^2}{\phi + B  }+\Delta r^q} - \phi - B}
\end{aligned}$$

**Comment by Unique-Divine** [comment]
Closing this as we decided to write swaps in terms of "reserves" and "assets" similar to regular xy=k since depth shift breaks some of the conditions we expected to hold true.
