### ISSUE TITLE
Different amount show when try to swap NUSD to USDT

### ISSUE THREAD

**Issue by reigister** [NibiruChain/nibiru#1238]
I try to swap NUSD to USDT. it show 10 NUSD to 28.0573 USDT but when i try to swap it. The amount USDT i got only 10.64USDT
what happen with this? 
![swap 10NUSD to 28 USDT](https://user-images.githubusercontent.com/78670969/227864989-4e07687c-741a-4151-beeb-d3622b8f4131.png)

**Comment by Unique-Divine** [comment]
Predicted price for stableswap pools have estimates in JS, so this should no longer be an issue

**Comment by reigister** [comment]
discord username : milakunis
