### ISSUE TITLE
docs: Create cookbook with the request json of all CosmWasm contracts for future reference

### ISSUE THREAD

**Issue by jgimeno** [NibiruChain/nibiru#1294]
CosmWasm contracts use json to send a request, this information is 
normally not well documented in general.

Create a folder called cookbook with all the requests that are supported.

**Comment by Unique-Divine** [comment]
Can you give a bit more info on the desired API for this ticket? I'm imagining some markdown with bash code blocks that use `nibid [tx/query] wasm`
