### ISSUE TITLE
Error when closing position

### ISSUE THREAD

**Issue by cgilbe27** [NibiruChain/nibiru#1400]
> — 05/26/2023 3:39 AM
 I am getting this error when closing the position.  To wear relevant clothes even though my position is approved. sampling only appears either from long or short position. The image on the board even though there are two long and short positions opened for the same currency pair.
- Chain: `nibiru-itn-1`
- User: `nibi1udlvlte3ll6taz5f6c7saw0lsj7penjsl23qnm`

![Image](https://github.com/NibiruChain/nibiru/assets/51418232/99ceb4ee-e79f-4e11-b14f-57deab278fdd)

Ref: https://discord.com/channels/947911971515293759/984839976615305276/1111574269923704902

**Comment by Unique-Divine** [comment]
Resolved in v0.21
