### ISSUE TITLE
feat(oracle): introduce new events

### ISSUE THREAD

**Issue by ruslan-sh-r** [NibiruChain/nibiru#1530]
Add events that can be used to track the following metrics for each validator:
* number of wins 
* number of misses
* number of abstains
* number of slashes 
* reward

**Comment by Unique-Divine** [comment]
- Need to be able to compare validator performance. A staker in the front-end could elect to delegate to a smaller validator with more consistent oracle performance/income
- THe current `QueryServer.MissCounter` only reveals misses but not wins or abstains
- Rewards likely separate event
