### ISSUE TITLE
error invalid proposal signature

### ISSUE THREAD

**Issue by KokosP** [NibiruChain/nibiru#1599]
after restoring a node from a snapshot, I get the following error in the log

10:51PM ERR failed to process message err="error invalid proposal signature" height=778982 module=consensus msg_type=*consensus.ProposalMessage peer=b316ff6b5a0715732fa02f990db94aef39e758b3 round=0
10:51PM ERR failed to process message err="error invalid proposal signature" height=778982 module=consensus msg_type=*consensus.ProposalMessage peer=134e3d389d2ef35ee057b1e2678df9376571233d round=0
10:51PM ERR failed to process message err="error invalid proposal signature" height=778982 module=consensus msg_type=*consensus.ProposalMessage peer=9086faf41c3698a2ac9a2e77fa66ce337682ae9f round=0
10:51PM ERR failed to process message err="error invalid proposal signature" height=778982 module=consensus msg_type=*consensus.ProposalMessage peer=e98617ca77c63899c6ac7edc3a1889d8d524b384 round=0
10:51PM ERR failed to process message err="error invalid proposal signature" height=778982 module=consensus msg_type=*consensus.ProposalMessage peer=a98484ac9cb8235bd6a65cdf7648107e3d14dab4 round=0
10:51PM ERR failed to process message err="error invalid proposal signature" height=778982 module=consensus msg_type=*consensus.ProposalMessage peer=bb1559d1a487586673a5f65518c62cd3e3b503a4 round=0
10:51PM ERR failed to process message err="error invalid proposal signature" height=778982 module=consensus msg_type=*consensus.ProposalMessage peer=c060180df8c01546c66d21ee307b09f700780f65 round=0
10:51PM ERR failed to process message err="error invalid proposal signature" height=778982 module=consensus msg_type=*consensus.ProposalMessage peer=5cd43fa2f6910e9aec268d347fb7d9797616a462 round=0
10:51PM ERR failed to process message err="error invalid proposal signature" height=778982 module=consensus msg_type=*consensus.ProposalMessage peer=4f8b55e56e4ca147bf8c36c1308fb634cdcd13d2 round=0
10:51PM ERR failed to process message err="error invalid proposal signature" height=778982 module=consensus msg_type=*consensus.ProposalMessage peer=40cca75f1bb9fd5c837d1cae1002693b21f1a560 round=0
10:51PM ERR failed to process message err="error invalid proposal signature" height=778982 module=consensus msg_type=*consensus.ProposalMessage peer=10675a6c798026ac44a496bddce00e622a522332 round=0
10:51PM INF Timed out dur=100 height=778982 module=consensus round=0 step=5

the node is working, there are no more errors in the logs

**Comment by Unique-Divine** [comment]
I see this note at the bottom of your ticket:
> "the node is working, there are no more errors in the logs"

Does this mean you got it resolved already?

**Comment by KokosP** [comment]
> I see this note at the bottom of your ticket:
> 
> > "the node is working, there are no more errors in the logs"
> 
> Does this mean you got it resolved already?

I didn’t write it exactly, the node is working, there are no other errors in the logs. There is an error, I don’t know how to solve the problem.

**Comment by KokosP** [comment]
![putty_p7BW4b9ByI](https://github.com/NibiruChain/nibiru/assets/108982468/e8ed8238-9ed2-4e28-bcb3-c18a9f89d934)

**Comment by Unique-Divine** [comment]
Closing as stale
