### ISSUE TITLE
take open perp fees from trade itself

### ISSUE THREAD

**Issue by elshenak** [NibiruChain/nibiru#1622]
When you perform a trade, the fees deduction is performed to your leftover balance. This causes an issue when you use all your balance to perform a trade. [Relates to ](https://github.com/NibiruChain/web-app/issues/711)

**Comment by Unique-Divine** [comment]
Described by https://github.com/NibiruChain/nibiru/issues/1618

**Comment by Unique-Divine** [comment]
Closed by https://github.com/NibiruChain/nibiru/pull/1718
