### ISSUE TITLE
Stake

### ISSUE THREAD

**Issue by SeyiGee** [NibiruChain/nibiru#1807]
Can't stake to more than one validator

**Comment by Unique-Divine** [comment]
Hi @SeyiGee, we need a bit more information. 
1. Which network are you referring to? Mainnet (`cataclysm-1`), Permanent Testnet (`nibiru-testnet-1`), or something else?
2. Which method are you using to stake? JavaScript `@nibiruchain/nibijs`, the CLI, or the [web app](https://app.nibiru.fi)?
3. And can you paste whatever error message you're getting and include any relevant screenshots?
