### ISSUE TITLE
bug(evm): de-synchronization between wasm bank balance and EVM account state

### ISSUE THREAD

**Issue by k-yang** [NibiruChain/nibiru#2133]
## Description

Transfer between regular base account and an account made from a Wasm contract

## Steps to Reproduce

1. bank send funds to a wasm account
```sh
nibid tx bank send \
nibi1zaavvzxez0elundtn32qnk9lkm8kmcsz44g7xl \
nibi14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9ssa9gcs \
1000000unibi \
--gas auto \
--gas-adjustment 1.5 \
--gas-prices 0.025unibi \
--yes | jq
```

2. query bank balances
```sh
nibid q bank balances nibi14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9ssa9gcs | jq
{
  "balances": [
    {
      "denom": "unibi",
      "amount": "1000000"
    }
  ],
  "pagination": {
    "next_key": null,
    "total": "0"
  }
}
```

3. query evm account
```sh
nibid q evm account nibi14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9ssa9gcs | jq
{
  "balance": "0",
  "balance_wei": "0",
  "code_hash": "0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470",
  "nonce": "0",
  "eth_address": "0x5A8D648DEE57b2fc90D98DC17fa887159b69638b",
  "bech32_address": "nibi14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9ssa9gcs"
}
```

The EVM account should have the same balance as the bank balance.

**Comment by Jason-Tariq** [comment]
Hello @k-yang  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by Unique-Divine** [comment]
Note that this is not related to any difference of actual funds. The GRPC query is simply retrieving the balance incorrectly by using `StateDB.GetAccount` instead of the bank balance query.

Easy fix here: https://github.com/NibiruChain/nibiru/pull/2134
