### ISSUE TITLE
test(stablecoin): Add more CLI test coverage

### ISSUE THREAD

**Issue by NibiruHeisenberg** [NibiruChain/nibiru#583]
- [ ] test(stablecoin): add mint stablecoin coverage
- [ ] test(stablecoin): add burn stablecoin coverage

https://github.com/NibiruChain/nibiru/blob/a8083852a2267db4521b00a5907a5e4541e54c30/x/stablecoin/client/cli/cli_test.go#L142

**Comment by Unique-Divine** [comment]
Not priority
