### ISSUE TITLE
change: AssetPair API refactoring

### ISSUE THREAD

**Issue by testinginprod** [NibiruChain/nibiru#799]
I propose to refactor `AssetPair`.

Remove it from proto files.

Make it a custom proto type we can use in place of `string`.

Make the `AssetPair` API safe to use, by unexporting fields. 

Current problems:
- pair somewhere is defined as string, somewhere else as `AssetPair`.
- code is cluttered by conversion to AssetPair to string, and string to AssetPair
- in some part of the code we use token0, token1
- Validation is needed everywhere because engineers are unsure when the AssetPair is safe to use.

Example implementation: 
```go
type AssetPair struct {
    t0 string // Fields are private to avoid bad initialization
    t1 string
}

func (p AssetPair) Token1() string { return p.t1 }

func (p AssetPair) String() string { ... } 

func NewAssetPair(token1, token2 string) (AssetPair, error)
```

**Comment by Unique-Divine** [comment]
This was completed successfully. Currently, the `asset.Pair` type is a type alias for `string` with functions that make it feel like we're working with a struct.
